# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2022-2030 Oplus. All rights reserved.

LINUXINCLUDE += -I$(srctree)/

obj-$(CONFIG_OPLUS_FEATURE_SIGKILL_DIAGNOSIS) += oplus_bsp_sigkill_diagnosis.o

oplus_bsp_sigkill_diagnosis-y := sigkill_diagnosis.o
