	obj-$(CONFIG_OPLUS_CHARGER_WIRELESS_PEN)	+= oplus_p9418.o
	obj-$(CONFIG_OPLUS_CHARGER_WIRELESS_RA9530)	+= oplus_ra9530.o
	obj-y	+= oplus_p922x.o
	obj-y	+= oplus_nu1619.o
	obj-y	+= oplus_chargepump.o

