# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-y += frame_info.o
obj-y += cluster_boost.o
obj-y += frame_boost.o
obj-y += frame_debug.o
obj-y += frame_group.o
