#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_NOVA) += novatek_common.o
obj-$(CONFIG_TOUCHPANEL_NOVA_NT36523_NOFLASH) += NT36523_noflash/

#endif
