# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

LINUXINCLUDE += -I$(srctree)/

obj-$(CONFIG_PROACTIVE_COMPACT) += oplus_bsp_proactive_compact.o

oplus_bsp_proactive_compact-y := proactive_compact.o