#ifndef __OPLUS_CHG_TRACK_H__
#define __OPLUS_CHG_TRACK_H__

#include <linux/version.h>
#include <linux/of.h>

#define OPLUS_CHG_TRACK_CURX_INFO_LEN 1536
#define TRACK_CHG_GET_THTS_TIME_TYPE 0
#define TRACK_CHG_GET_LAST_TIME_TYPE 1

struct oplus_chg_track;
struct oplus_monitor;

enum oplus_chg_track_cmd_error {
	TRACK_CMD_ACK_OK,
	TRACK_CMD_ERROR_CHIP_NULL = 1,
	TRACK_CMD_ERROR_DATA_NULL,
	TRACK_CMD_ERROR_DATA_INVALID,
	TRACK_CMD_ERROR_TIME_OUT,
};

enum oplus_chg_track_info_type {
	TRACK_NOTIFY_TYPE_DEFAULT,
	TRACK_NOTIFY_TYPE_SOC_JUMP,
	TRACK_NOTIFY_TYPE_GENERAL_RECORD,
	TRACK_NOTIFY_TYPE_NO_CHARGING,
	TRACK_NOTIFY_TYPE_CHARGING_SLOW,
	TRACK_NOTIFY_TYPE_CHARGING_BREAK,
	TRACK_NOTIFY_TYPE_DEVICE_ABNORMAL,
	TRACK_NOTIFY_TYPE_SOFTWARE_ABNORMAL,
	TRACK_NOTIFY_TYPE_MAX,
};

enum oplus_chg_track_info_flag {
	TRACK_NOTIFY_FLAG_DEFAULT,

	TRACK_NOTIFY_FLAG_SOC_JUMP_FIRST,
	TRACK_NOTIFY_FLAG_UI_SOC_LOAD_JUMP = TRACK_NOTIFY_FLAG_SOC_JUMP_FIRST,
	TRACK_NOTIFY_FLAG_SOC_JUMP,
	TRACK_NOTIFY_FLAG_UI_SOC_JUMP,
	TRACK_NOTIFY_FLAG_UI_SOC_TO_SOC_JUMP,
	TRACK_NOTIFY_FLAG_SOC_JUMP_LAST = TRACK_NOTIFY_FLAG_UI_SOC_TO_SOC_JUMP,

	TRACK_NOTIFY_FLAG_GENERAL_RECORD_FIRST,
	TRACK_NOTIFY_FLAG_CHARGER_INFO = TRACK_NOTIFY_FLAG_GENERAL_RECORD_FIRST,
	TRACK_NOTIFY_FLAG_UISOC_KEEP_1_T_INFO,
	TRACK_NOTIFY_FLAG_VBATT_TOO_LOW_INFO,
	TRACK_NOTIFY_FLAG_USBTEMP_INFO,
	TRACK_NOTIFY_FLAG_VBATT_DIFF_OVER_INFO,
	TRACK_NOTIFY_FLAG_SERVICE_UPDATE_WLS_THIRD_INFO,
	TRACK_NOTIFY_FLAG_WLS_INFO,
	TRACK_NOTIFY_FLAG_PARALLELCHG_FOLDMODE_INFO,
	TRACK_NOTIFY_FLAG_MMI_CHG_INFO,
	TRACK_NOTIFY_FLAG_SLOW_CHG_INFO,
	TRACK_NOTIFY_FLAG_CHG_CYCLE_INFO,
	TRACK_NOTIFY_FLAG_TTF_INFO,
	TRACK_NOTIFY_FLAG_UISOH_INFO,
	TRACK_NOTIFY_FLAG_GENERAL_RECORD_LAST = TRACK_NOTIFY_FLAG_UISOH_INFO,

	TRACK_NOTIFY_FLAG_NO_CHARGING_FIRST,
	TRACK_NOTIFY_FLAG_NO_CHARGING = TRACK_NOTIFY_FLAG_NO_CHARGING_FIRST,
	TRACK_NOTIFY_FLAG_NO_CHARGING_OTG_ONLINE,
	TRACK_NOTIFY_FLAG_NO_CHARGING_VBATT_LEAK,
	TRACK_NOTIFY_FLAG_NO_CHARGING_LAST = TRACK_NOTIFY_FLAG_NO_CHARGING_VBATT_LEAK,

	TRACK_NOTIFY_FLAG_CHARGING_SLOW_FIRST,
	TRACK_NOTIFY_FLAG_CHG_SLOW_TBATT_WARM = TRACK_NOTIFY_FLAG_CHARGING_SLOW_FIRST,
	TRACK_NOTIFY_FLAG_CHG_SLOW_TBATT_COLD,
	TRACK_NOTIFY_FLAG_CHG_SLOW_NON_STANDARD_PA,
	TRACK_NOTIFY_FLAG_CHG_SLOW_BATT_CAP_HIGH,
	TRACK_NOTIFY_FLAG_CHG_SLOW_COOLDOWN,
	TRACK_NOTIFY_FLAG_CHG_SLOW_WLS_SKEW,
	TRACK_NOTIFY_FLAG_CHG_SLOW_VERITY_FAIL,
	TRACK_NOTIFY_FLAG_CHG_SLOW_OTHER,
	TRACK_NOTIFY_FLAG_CHARGING_SLOW_LAST = TRACK_NOTIFY_FLAG_CHG_SLOW_OTHER,

	TRACK_NOTIFY_FLAG_CHARGING_BREAK_FIRST,
	TRACK_NOTIFY_FLAG_FAST_CHARGING_BREAK = TRACK_NOTIFY_FLAG_CHARGING_BREAK_FIRST,
	TRACK_NOTIFY_FLAG_GENERAL_CHARGING_BREAK,
	TRACK_NOTIFY_FLAG_WLS_CHARGING_BREAK,
	TRACK_NOTIFY_FLAG_CHG_FEED_LIQUOR,
	TRACK_NOTIFY_FLAG_CHARGING_BREAK_LAST = TRACK_NOTIFY_FLAG_CHG_FEED_LIQUOR,

	TRACK_NOTIFY_FLAG_DEVICE_ABNORMAL_FIRST,
	TRACK_NOTIFY_FLAG_WLS_ABNORMAL = TRACK_NOTIFY_FLAG_DEVICE_ABNORMAL_FIRST,
	TRACK_NOTIFY_FLAG_GPIO_ABNORMAL,
	TRACK_NOTIFY_FLAG_CP_ABNORMAL,
	TRACK_NOTIFY_FLAG_PLAT_PMIC_ABNORMAL,
	TRACK_NOTIFY_FLAG_EXTERN_PMIC_ABNORMAL,
	TRACK_NOTIFY_FLAG_GAGUE_ABNORMAL,
	TRACK_NOTIFY_FLAG_DCHG_ABNORMAL,
	TRACK_NOTIFY_FLAG_PARALLEL_UNBALANCE_ABNORMAL,
	TRACK_NOTIFY_FLAG_MOS_ERROR_ABNORMAL,
	TRACK_NOTIFY_FLAG_HK_ABNORMAL,
	TRACK_NOTIFY_FLAG_UFCS_IC_ABNORMAL,
	TRACK_NOTIFY_FLAG_ADAPTER_ABNORMAL,
	TRACK_NOTIFY_FLAG_DEVICE_ABNORMAL_LAST = TRACK_NOTIFY_FLAG_ADAPTER_ABNORMAL,

	TRACK_NOTIFY_FLAG_SOFTWARE_ABNORMAL_FIRST,
	TRACK_NOTIFY_FLAG_UFCS_ABNORMAL = TRACK_NOTIFY_FLAG_SOFTWARE_ABNORMAL_FIRST,
	TRACK_NOTIFY_FLAG_COOLDOWN_ABNORMAL,
	TRACK_NOTIFY_FLAG_SMART_CHG_ABNORMAL,
	TRACK_NOTIFY_FLAG_WLS_THIRD_ENCRY_ABNORMAL,
	TRACK_NOTIFY_FLAG_PEN_MATCH_STATE_ABNORMAL,
	TRACK_NOTIFY_FLAG_PPS_ABNORMAL,
	TRACK_NOTIFY_FLAG_FASTCHG_START_ABNORMAL,
	TRACK_NOTIFY_FLAG_DUAL_CHAN_ABNORMAL,
	TRACK_NOTIFY_FLAG_DUMMY_START_ABNORMAL,
	TRACK_NOTIFY_FLAG_SOFTWARE_ABNORMAL_LAST = TRACK_NOTIFY_FLAG_DUMMY_START_ABNORMAL,

	TRACK_NOTIFY_FLAG_MAX_CNT,


};

enum oplus_chg_liquid_intake_track_cmd {
	TRACK_CMD_LIQUID_INTAKE,
	TRACK_CMD_CLEAR_TIMER,
};

enum oplus_chg_liquid_intake_track_data {
	TRACK_DATA_PLUGOUT_INTERVAL,
	TRACK_DATA_PLUGOUT_WIRE_CONNECT_STATE,
	TRACK_DATA_PLUGOUT_MAX
};

typedef struct {
	unsigned int type_reason;
	unsigned int flag_reason;
	unsigned char crux_info[OPLUS_CHG_TRACK_CURX_INFO_LEN];
} __attribute__ ((packed)) oplus_chg_track_trigger;

int oplus_chg_track_comm_monitor(struct oplus_monitor *monitor);
int oplus_chg_track_check_wired_charging_break(int vbus_rising);
int oplus_chg_track_set_fastchg_break_code(int fastchg_break_code);
int oplus_chg_track_driver_init(struct oplus_monitor *monitor);
int oplus_chg_track_driver_exit(struct oplus_monitor *monitor);
int oplus_chg_track_set_uisoc_1_start(struct oplus_monitor *monitor);
int oplus_chg_track_charge_full(struct oplus_monitor *monitor);
int oplus_chg_track_cal_tbatt_status(struct oplus_monitor *monitor);
int oplus_chg_track_handle_wired_type_info(struct oplus_monitor *monitor, int type);
int oplus_chg_track_aging_ffc_check(struct oplus_monitor *monitor, int step);
int oplus_chg_track_record_ffc_end_time(struct oplus_monitor *monitor);
int oplus_chg_track_record_ffc_soc(struct oplus_monitor *monitor,
	int main_soc, int sub_soc, bool start);
int oplus_chg_track_record_dual_chan_start(struct oplus_monitor *monitor);
int oplus_chg_track_record_dual_chan_end(struct oplus_monitor *monitor);
int oplus_chg_water_inlet_detect(int reason, int plugin_count);
int oplus_chg_track_set_app_info(const char *buf);
int oplus_chg_track_olc_config_set(const char *buf);
int oplus_chg_track_olc_config_get(char *buf);
int oplus_chg_track_time_zone_set(const char *buf);
int oplus_chg_track_time_zone_get(char *buf);
struct dentry *oplus_chg_track_get_debugfs_root(void);
int oplus_chg_track_set_hidl_info(const char *buf, size_t count);
int oplus_chg_track_check_wls_charging_break(int wls_connect);

#endif /* __OPLUS_CHG_TRACK_H__ */
