# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

obj-$(CONFIG_OPLUS_FEATURE_FEEDBACK) 	+= feedback/
obj-$(CONFIG_OPLUS_FEATURE_OPROJECT) 	+= oplus_project/
obj-$(CONFIG_OPLUS_FEATURE_CMDLINE)     += cmdline_parser/
obj-$(CONFIG_OPLUS_FEATURE_PROJECTINFO)	+=  project_info/
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK) += oplus_mm_fb/
obj-$(CONFIG_OPLUS_PARAM_READ_WRITE)    += param/
