# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

#ifdef OPLUS_FEATURE_ESIM
obj-$(CONFIG_OPLUS_GPIO)    +=  oplus_gpio/
#endif /* OPLUS_FEATURE_ESIM */

#ifdef OPLUS_FEATURE_SIM_DETECT
obj-$(CONFIG_SIM_DETECT)	+= sim_detect.o
#endif /* OPLUS_FEATURE_SIM_DETECT */