/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netlink_msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "netlink_msg.pb-c.h"
void   netlink__proto__message_header__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__MessageHeader init_value = NETLINK__PROTO__MESSAGE_HEADER__INIT;
  *(Netlink__Proto__MessageHeader*)message = init_value;
}
size_t netlink__proto__message_header__get_packed_size
                     (const Netlink__Proto__MessageHeader *message)
{
  assert(message->base.descriptor == &netlink__proto__message_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__message_header__pack
                     (const Netlink__Proto__MessageHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__message_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__message_header__pack_to_buffer
                     (const Netlink__Proto__MessageHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__message_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__MessageHeader *
       netlink__proto__message_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__MessageHeader *)
     protobuf_c_message_unpack (&netlink__proto__message_header__descriptor,
                                allocator, len, data);
}
void   netlink__proto__message_header__free_unpacked
                     (Netlink__Proto__MessageHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__message_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__request_set_dpi_uid__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__RequestSetDpiUid init_value = NETLINK__PROTO__REQUEST_SET_DPI_UID__INIT;
  *(Netlink__Proto__RequestSetDpiUid*)message = init_value;
}
size_t netlink__proto__request_set_dpi_uid__get_packed_size
                     (const Netlink__Proto__RequestSetDpiUid *message)
{
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_uid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__request_set_dpi_uid__pack
                     (const Netlink__Proto__RequestSetDpiUid *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_uid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__request_set_dpi_uid__pack_to_buffer
                     (const Netlink__Proto__RequestSetDpiUid *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_uid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__RequestSetDpiUid *
       netlink__proto__request_set_dpi_uid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__RequestSetDpiUid *)
     protobuf_c_message_unpack (&netlink__proto__request_set_dpi_uid__descriptor,
                                allocator, len, data);
}
void   netlink__proto__request_set_dpi_uid__free_unpacked
                     (Netlink__Proto__RequestSetDpiUid *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_uid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__request_get_dpi_stream_speed__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__RequestGetDpiStreamSpeed init_value = NETLINK__PROTO__REQUEST_GET_DPI_STREAM_SPEED__INIT;
  *(Netlink__Proto__RequestGetDpiStreamSpeed*)message = init_value;
}
size_t netlink__proto__request_get_dpi_stream_speed__get_packed_size
                     (const Netlink__Proto__RequestGetDpiStreamSpeed *message)
{
  assert(message->base.descriptor == &netlink__proto__request_get_dpi_stream_speed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__request_get_dpi_stream_speed__pack
                     (const Netlink__Proto__RequestGetDpiStreamSpeed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__request_get_dpi_stream_speed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__request_get_dpi_stream_speed__pack_to_buffer
                     (const Netlink__Proto__RequestGetDpiStreamSpeed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__request_get_dpi_stream_speed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__RequestGetDpiStreamSpeed *
       netlink__proto__request_get_dpi_stream_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__RequestGetDpiStreamSpeed *)
     protobuf_c_message_unpack (&netlink__proto__request_get_dpi_stream_speed__descriptor,
                                allocator, len, data);
}
void   netlink__proto__request_get_dpi_stream_speed__free_unpacked
                     (Netlink__Proto__RequestGetDpiStreamSpeed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__request_get_dpi_stream_speed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__request_set_log_steam_ip__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__RequestSetLogSteamIp init_value = NETLINK__PROTO__REQUEST_SET_LOG_STEAM_IP__INIT;
  *(Netlink__Proto__RequestSetLogSteamIp*)message = init_value;
}
size_t netlink__proto__request_set_log_steam_ip__get_packed_size
                     (const Netlink__Proto__RequestSetLogSteamIp *message)
{
  assert(message->base.descriptor == &netlink__proto__request_set_log_steam_ip__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__request_set_log_steam_ip__pack
                     (const Netlink__Proto__RequestSetLogSteamIp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__request_set_log_steam_ip__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__request_set_log_steam_ip__pack_to_buffer
                     (const Netlink__Proto__RequestSetLogSteamIp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__request_set_log_steam_ip__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__RequestSetLogSteamIp *
       netlink__proto__request_set_log_steam_ip__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__RequestSetLogSteamIp *)
     protobuf_c_message_unpack (&netlink__proto__request_set_log_steam_ip__descriptor,
                                allocator, len, data);
}
void   netlink__proto__request_set_log_steam_ip__free_unpacked
                     (Netlink__Proto__RequestSetLogSteamIp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__request_set_log_steam_ip__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__request_get_all_uid_speed__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__RequestGetAllUidSpeed init_value = NETLINK__PROTO__REQUEST_GET_ALL_UID_SPEED__INIT;
  *(Netlink__Proto__RequestGetAllUidSpeed*)message = init_value;
}
size_t netlink__proto__request_get_all_uid_speed__get_packed_size
                     (const Netlink__Proto__RequestGetAllUidSpeed *message)
{
  assert(message->base.descriptor == &netlink__proto__request_get_all_uid_speed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__request_get_all_uid_speed__pack
                     (const Netlink__Proto__RequestGetAllUidSpeed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__request_get_all_uid_speed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__request_get_all_uid_speed__pack_to_buffer
                     (const Netlink__Proto__RequestGetAllUidSpeed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__request_get_all_uid_speed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__RequestGetAllUidSpeed *
       netlink__proto__request_get_all_uid_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__RequestGetAllUidSpeed *)
     protobuf_c_message_unpack (&netlink__proto__request_get_all_uid_speed__descriptor,
                                allocator, len, data);
}
void   netlink__proto__request_get_all_uid_speed__free_unpacked
                     (Netlink__Proto__RequestGetAllUidSpeed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__request_get_all_uid_speed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__request_set_dpi_match_all_uid_eable__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__RequestSetDpiMatchAllUidEable init_value = NETLINK__PROTO__REQUEST_SET_DPI_MATCH_ALL_UID_EABLE__INIT;
  *(Netlink__Proto__RequestSetDpiMatchAllUidEable*)message = init_value;
}
size_t netlink__proto__request_set_dpi_match_all_uid_eable__get_packed_size
                     (const Netlink__Proto__RequestSetDpiMatchAllUidEable *message)
{
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_match_all_uid_eable__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__request_set_dpi_match_all_uid_eable__pack
                     (const Netlink__Proto__RequestSetDpiMatchAllUidEable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_match_all_uid_eable__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__request_set_dpi_match_all_uid_eable__pack_to_buffer
                     (const Netlink__Proto__RequestSetDpiMatchAllUidEable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_match_all_uid_eable__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__RequestSetDpiMatchAllUidEable *
       netlink__proto__request_set_dpi_match_all_uid_eable__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__RequestSetDpiMatchAllUidEable *)
     protobuf_c_message_unpack (&netlink__proto__request_set_dpi_match_all_uid_eable__descriptor,
                                allocator, len, data);
}
void   netlink__proto__request_set_dpi_match_all_uid_eable__free_unpacked
                     (Netlink__Proto__RequestSetDpiMatchAllUidEable *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__request_set_dpi_match_all_uid_eable__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__request_message__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__RequestMessage init_value = NETLINK__PROTO__REQUEST_MESSAGE__INIT;
  *(Netlink__Proto__RequestMessage*)message = init_value;
}
size_t netlink__proto__request_message__get_packed_size
                     (const Netlink__Proto__RequestMessage *message)
{
  assert(message->base.descriptor == &netlink__proto__request_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__request_message__pack
                     (const Netlink__Proto__RequestMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__request_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__request_message__pack_to_buffer
                     (const Netlink__Proto__RequestMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__request_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__RequestMessage *
       netlink__proto__request_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__RequestMessage *)
     protobuf_c_message_unpack (&netlink__proto__request_message__descriptor,
                                allocator, len, data);
}
void   netlink__proto__request_message__free_unpacked
                     (Netlink__Proto__RequestMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__request_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__dpi_speed_item__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__DpiSpeedItem init_value = NETLINK__PROTO__DPI_SPEED_ITEM__INIT;
  *(Netlink__Proto__DpiSpeedItem*)message = init_value;
}
size_t netlink__proto__dpi_speed_item__get_packed_size
                     (const Netlink__Proto__DpiSpeedItem *message)
{
  assert(message->base.descriptor == &netlink__proto__dpi_speed_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__dpi_speed_item__pack
                     (const Netlink__Proto__DpiSpeedItem *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__dpi_speed_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__dpi_speed_item__pack_to_buffer
                     (const Netlink__Proto__DpiSpeedItem *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__dpi_speed_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__DpiSpeedItem *
       netlink__proto__dpi_speed_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__DpiSpeedItem *)
     protobuf_c_message_unpack (&netlink__proto__dpi_speed_item__descriptor,
                                allocator, len, data);
}
void   netlink__proto__dpi_speed_item__free_unpacked
                     (Netlink__Proto__DpiSpeedItem *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__dpi_speed_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__response_get_dpi_stream_speed__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__ResponseGetDpiStreamSpeed init_value = NETLINK__PROTO__RESPONSE_GET_DPI_STREAM_SPEED__INIT;
  *(Netlink__Proto__ResponseGetDpiStreamSpeed*)message = init_value;
}
size_t netlink__proto__response_get_dpi_stream_speed__get_packed_size
                     (const Netlink__Proto__ResponseGetDpiStreamSpeed *message)
{
  assert(message->base.descriptor == &netlink__proto__response_get_dpi_stream_speed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__response_get_dpi_stream_speed__pack
                     (const Netlink__Proto__ResponseGetDpiStreamSpeed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__response_get_dpi_stream_speed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__response_get_dpi_stream_speed__pack_to_buffer
                     (const Netlink__Proto__ResponseGetDpiStreamSpeed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__response_get_dpi_stream_speed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__ResponseGetDpiStreamSpeed *
       netlink__proto__response_get_dpi_stream_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__ResponseGetDpiStreamSpeed *)
     protobuf_c_message_unpack (&netlink__proto__response_get_dpi_stream_speed__descriptor,
                                allocator, len, data);
}
void   netlink__proto__response_get_dpi_stream_speed__free_unpacked
                     (Netlink__Proto__ResponseGetDpiStreamSpeed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__response_get_dpi_stream_speed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__response_get_wzry_server_ip__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__ResponseGetWzryServerIp init_value = NETLINK__PROTO__RESPONSE_GET_WZRY_SERVER_IP__INIT;
  *(Netlink__Proto__ResponseGetWzryServerIp*)message = init_value;
}
size_t netlink__proto__response_get_wzry_server_ip__get_packed_size
                     (const Netlink__Proto__ResponseGetWzryServerIp *message)
{
  assert(message->base.descriptor == &netlink__proto__response_get_wzry_server_ip__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__response_get_wzry_server_ip__pack
                     (const Netlink__Proto__ResponseGetWzryServerIp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__response_get_wzry_server_ip__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__response_get_wzry_server_ip__pack_to_buffer
                     (const Netlink__Proto__ResponseGetWzryServerIp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__response_get_wzry_server_ip__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__ResponseGetWzryServerIp *
       netlink__proto__response_get_wzry_server_ip__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__ResponseGetWzryServerIp *)
     protobuf_c_message_unpack (&netlink__proto__response_get_wzry_server_ip__descriptor,
                                allocator, len, data);
}
void   netlink__proto__response_get_wzry_server_ip__free_unpacked
                     (Netlink__Proto__ResponseGetWzryServerIp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__response_get_wzry_server_ip__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__game_delay_stats__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__GameDelayStats init_value = NETLINK__PROTO__GAME_DELAY_STATS__INIT;
  *(Netlink__Proto__GameDelayStats*)message = init_value;
}
size_t netlink__proto__game_delay_stats__get_packed_size
                     (const Netlink__Proto__GameDelayStats *message)
{
  assert(message->base.descriptor == &netlink__proto__game_delay_stats__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__game_delay_stats__pack
                     (const Netlink__Proto__GameDelayStats *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__game_delay_stats__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__game_delay_stats__pack_to_buffer
                     (const Netlink__Proto__GameDelayStats *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__game_delay_stats__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__GameDelayStats *
       netlink__proto__game_delay_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__GameDelayStats *)
     protobuf_c_message_unpack (&netlink__proto__game_delay_stats__descriptor,
                                allocator, len, data);
}
void   netlink__proto__game_delay_stats__free_unpacked
                     (Netlink__Proto__GameDelayStats *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__game_delay_stats__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__response_get_game_delay__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__ResponseGetGameDelay init_value = NETLINK__PROTO__RESPONSE_GET_GAME_DELAY__INIT;
  *(Netlink__Proto__ResponseGetGameDelay*)message = init_value;
}
size_t netlink__proto__response_get_game_delay__get_packed_size
                     (const Netlink__Proto__ResponseGetGameDelay *message)
{
  assert(message->base.descriptor == &netlink__proto__response_get_game_delay__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__response_get_game_delay__pack
                     (const Netlink__Proto__ResponseGetGameDelay *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__response_get_game_delay__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__response_get_game_delay__pack_to_buffer
                     (const Netlink__Proto__ResponseGetGameDelay *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__response_get_game_delay__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__ResponseGetGameDelay *
       netlink__proto__response_get_game_delay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__ResponseGetGameDelay *)
     protobuf_c_message_unpack (&netlink__proto__response_get_game_delay__descriptor,
                                allocator, len, data);
}
void   netlink__proto__response_get_game_delay__free_unpacked
                     (Netlink__Proto__ResponseGetGameDelay *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__response_get_game_delay__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__response_message__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__ResponseMessage init_value = NETLINK__PROTO__RESPONSE_MESSAGE__INIT;
  *(Netlink__Proto__ResponseMessage*)message = init_value;
}
size_t netlink__proto__response_message__get_packed_size
                     (const Netlink__Proto__ResponseMessage *message)
{
  assert(message->base.descriptor == &netlink__proto__response_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__response_message__pack
                     (const Netlink__Proto__ResponseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__response_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__response_message__pack_to_buffer
                     (const Netlink__Proto__ResponseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__response_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__ResponseMessage *
       netlink__proto__response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__ResponseMessage *)
     protobuf_c_message_unpack (&netlink__proto__response_message__descriptor,
                                allocator, len, data);
}
void   netlink__proto__response_message__free_unpacked
                     (Netlink__Proto__ResponseMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__response_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__inform_message__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__InformMessage init_value = NETLINK__PROTO__INFORM_MESSAGE__INIT;
  *(Netlink__Proto__InformMessage*)message = init_value;
}
size_t netlink__proto__inform_message__get_packed_size
                     (const Netlink__Proto__InformMessage *message)
{
  assert(message->base.descriptor == &netlink__proto__inform_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__inform_message__pack
                     (const Netlink__Proto__InformMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__inform_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__inform_message__pack_to_buffer
                     (const Netlink__Proto__InformMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__inform_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__InformMessage *
       netlink__proto__inform_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__InformMessage *)
     protobuf_c_message_unpack (&netlink__proto__inform_message__descriptor,
                                allocator, len, data);
}
void   netlink__proto__inform_message__free_unpacked
                     (Netlink__Proto__InformMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__inform_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__notify_wzry_server_ip__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__NotifyWzryServerIp init_value = NETLINK__PROTO__NOTIFY_WZRY_SERVER_IP__INIT;
  *(Netlink__Proto__NotifyWzryServerIp*)message = init_value;
}
size_t netlink__proto__notify_wzry_server_ip__get_packed_size
                     (const Netlink__Proto__NotifyWzryServerIp *message)
{
  assert(message->base.descriptor == &netlink__proto__notify_wzry_server_ip__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__notify_wzry_server_ip__pack
                     (const Netlink__Proto__NotifyWzryServerIp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__notify_wzry_server_ip__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__notify_wzry_server_ip__pack_to_buffer
                     (const Netlink__Proto__NotifyWzryServerIp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__notify_wzry_server_ip__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__NotifyWzryServerIp *
       netlink__proto__notify_wzry_server_ip__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__NotifyWzryServerIp *)
     protobuf_c_message_unpack (&netlink__proto__notify_wzry_server_ip__descriptor,
                                allocator, len, data);
}
void   netlink__proto__notify_wzry_server_ip__free_unpacked
                     (Netlink__Proto__NotifyWzryServerIp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__notify_wzry_server_ip__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netlink__proto__notify_message__init
                     (ProtobufCMessage         *message)
{
  static const Netlink__Proto__NotifyMessage init_value = NETLINK__PROTO__NOTIFY_MESSAGE__INIT;
  *(Netlink__Proto__NotifyMessage*)message = init_value;
}
size_t netlink__proto__notify_message__get_packed_size
                     (const Netlink__Proto__NotifyMessage *message)
{
  assert(message->base.descriptor == &netlink__proto__notify_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netlink__proto__notify_message__pack
                     (const Netlink__Proto__NotifyMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &netlink__proto__notify_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netlink__proto__notify_message__pack_to_buffer
                     (const Netlink__Proto__NotifyMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &netlink__proto__notify_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Netlink__Proto__NotifyMessage *
       netlink__proto__notify_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Netlink__Proto__NotifyMessage *)
     protobuf_c_message_unpack (&netlink__proto__notify_message__descriptor,
                                allocator, len, data);
}
void   netlink__proto__notify_message__free_unpacked
                     (Netlink__Proto__NotifyMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &netlink__proto__notify_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor netlink__proto__message_header__field_descriptors[3] =
{
  {
    "requestId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__MessageHeader, requestid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retCode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__MessageHeader, retcode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__MessageHeader, eventid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__message_header__field_indices_by_name[] = {
  2,   /* field[2] = eventId */
  0,   /* field[0] = requestId */
  1,   /* field[1] = retCode */
};
static const ProtobufCIntRange netlink__proto__message_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor netlink__proto__message_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.MessageHeader",
  "MessageHeader",
  "Netlink__Proto__MessageHeader",
  "netlink.proto",
  sizeof(Netlink__Proto__MessageHeader),
  3,
  netlink__proto__message_header__field_descriptors,
  netlink__proto__message_header__field_indices_by_name,
  1,  netlink__proto__message_header__number_ranges,
  (ProtobufCMessageInit) netlink__proto__message_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__request_set_dpi_uid__field_descriptors[3] =
{
  {
    "tmgpSgameUid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestSetDpiUid, tmgpsgameuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logkitUid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestSetDpiUid, logkituid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "haytapMarketUid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestSetDpiUid, haytapmarketuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__request_set_dpi_uid__field_indices_by_name[] = {
  2,   /* field[2] = haytapMarketUid */
  1,   /* field[1] = logkitUid */
  0,   /* field[0] = tmgpSgameUid */
};
static const ProtobufCIntRange netlink__proto__request_set_dpi_uid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor netlink__proto__request_set_dpi_uid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.RequestSetDpiUid",
  "RequestSetDpiUid",
  "Netlink__Proto__RequestSetDpiUid",
  "netlink.proto",
  sizeof(Netlink__Proto__RequestSetDpiUid),
  3,
  netlink__proto__request_set_dpi_uid__field_descriptors,
  netlink__proto__request_set_dpi_uid__field_indices_by_name,
  1,  netlink__proto__request_set_dpi_uid__number_ranges,
  (ProtobufCMessageInit) netlink__proto__request_set_dpi_uid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__request_get_dpi_stream_speed__field_descriptors[3] =
{
  {
    "ifidx",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Netlink__Proto__RequestGetDpiStreamSpeed, n_ifidx),
    offsetof(Netlink__Proto__RequestGetDpiStreamSpeed, ifidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Netlink__Proto__RequestGetDpiStreamSpeed, n_uid),
    offsetof(Netlink__Proto__RequestGetDpiStreamSpeed, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed_size",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestGetDpiStreamSpeed, speed_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__request_get_dpi_stream_speed__field_indices_by_name[] = {
  0,   /* field[0] = ifidx */
  2,   /* field[2] = speed_size */
  1,   /* field[1] = uid */
};
static const ProtobufCIntRange netlink__proto__request_get_dpi_stream_speed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor netlink__proto__request_get_dpi_stream_speed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.RequestGetDpiStreamSpeed",
  "RequestGetDpiStreamSpeed",
  "Netlink__Proto__RequestGetDpiStreamSpeed",
  "netlink.proto",
  sizeof(Netlink__Proto__RequestGetDpiStreamSpeed),
  3,
  netlink__proto__request_get_dpi_stream_speed__field_descriptors,
  netlink__proto__request_get_dpi_stream_speed__field_indices_by_name,
  1,  netlink__proto__request_get_dpi_stream_speed__number_ranges,
  (ProtobufCMessageInit) netlink__proto__request_get_dpi_stream_speed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__request_set_log_steam_ip__field_descriptors[2] =
{
  {
    "hostName",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestSetLogSteamIp, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipAddr",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Netlink__Proto__RequestSetLogSteamIp, n_ipaddr),
    offsetof(Netlink__Proto__RequestSetLogSteamIp, ipaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__request_set_log_steam_ip__field_indices_by_name[] = {
  0,   /* field[0] = hostName */
  1,   /* field[1] = ipAddr */
};
static const ProtobufCIntRange netlink__proto__request_set_log_steam_ip__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor netlink__proto__request_set_log_steam_ip__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.RequestSetLogSteamIp",
  "RequestSetLogSteamIp",
  "Netlink__Proto__RequestSetLogSteamIp",
  "netlink.proto",
  sizeof(Netlink__Proto__RequestSetLogSteamIp),
  2,
  netlink__proto__request_set_log_steam_ip__field_descriptors,
  netlink__proto__request_set_log_steam_ip__field_indices_by_name,
  1,  netlink__proto__request_set_log_steam_ip__number_ranges,
  (ProtobufCMessageInit) netlink__proto__request_set_log_steam_ip__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__request_get_all_uid_speed__field_descriptors[2] =
{
  {
    "ifidx",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Netlink__Proto__RequestGetAllUidSpeed, n_ifidx),
    offsetof(Netlink__Proto__RequestGetAllUidSpeed, ifidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed_size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestGetAllUidSpeed, speed_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__request_get_all_uid_speed__field_indices_by_name[] = {
  0,   /* field[0] = ifidx */
  1,   /* field[1] = speed_size */
};
static const ProtobufCIntRange netlink__proto__request_get_all_uid_speed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor netlink__proto__request_get_all_uid_speed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.RequestGetAllUidSpeed",
  "RequestGetAllUidSpeed",
  "Netlink__Proto__RequestGetAllUidSpeed",
  "netlink.proto",
  sizeof(Netlink__Proto__RequestGetAllUidSpeed),
  2,
  netlink__proto__request_get_all_uid_speed__field_descriptors,
  netlink__proto__request_get_all_uid_speed__field_indices_by_name,
  1,  netlink__proto__request_get_all_uid_speed__number_ranges,
  (ProtobufCMessageInit) netlink__proto__request_get_all_uid_speed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__request_set_dpi_match_all_uid_eable__field_descriptors[1] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestSetDpiMatchAllUidEable, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__request_set_dpi_match_all_uid_eable__field_indices_by_name[] = {
  0,   /* field[0] = enable */
};
static const ProtobufCIntRange netlink__proto__request_set_dpi_match_all_uid_eable__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netlink__proto__request_set_dpi_match_all_uid_eable__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.RequestSetDpiMatchAllUidEable",
  "RequestSetDpiMatchAllUidEable",
  "Netlink__Proto__RequestSetDpiMatchAllUidEable",
  "netlink.proto",
  sizeof(Netlink__Proto__RequestSetDpiMatchAllUidEable),
  1,
  netlink__proto__request_set_dpi_match_all_uid_eable__field_descriptors,
  netlink__proto__request_set_dpi_match_all_uid_eable__field_indices_by_name,
  1,  netlink__proto__request_set_dpi_match_all_uid_eable__number_ranges,
  (ProtobufCMessageInit) netlink__proto__request_set_dpi_match_all_uid_eable__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__request_message__field_descriptors[6] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__RequestMessage, header),
    &netlink__proto__message_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requsetSetDpiUid",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__RequestMessage, request_data_case),
    offsetof(Netlink__Proto__RequestMessage, requsetsetdpiuid),
    &netlink__proto__request_set_dpi_uid__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestGetDpiStreamSpeed",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__RequestMessage, request_data_case),
    offsetof(Netlink__Proto__RequestMessage, requestgetdpistreamspeed),
    &netlink__proto__request_get_dpi_stream_speed__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestSetLogSteamIp",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__RequestMessage, request_data_case),
    offsetof(Netlink__Proto__RequestMessage, requestsetlogsteamip),
    &netlink__proto__request_set_log_steam_ip__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestGetAllUidSpeed",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__RequestMessage, request_data_case),
    offsetof(Netlink__Proto__RequestMessage, requestgetalluidspeed),
    &netlink__proto__request_get_all_uid_speed__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestSetDpiMatchAllUidEable",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__RequestMessage, request_data_case),
    offsetof(Netlink__Proto__RequestMessage, requestsetdpimatchalluideable),
    &netlink__proto__request_set_dpi_match_all_uid_eable__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__request_message__field_indices_by_name[] = {
  0,   /* field[0] = header */
  4,   /* field[4] = requestGetAllUidSpeed */
  2,   /* field[2] = requestGetDpiStreamSpeed */
  5,   /* field[5] = requestSetDpiMatchAllUidEable */
  3,   /* field[3] = requestSetLogSteamIp */
  1,   /* field[1] = requsetSetDpiUid */
};
static const ProtobufCIntRange netlink__proto__request_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 1 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor netlink__proto__request_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.RequestMessage",
  "RequestMessage",
  "Netlink__Proto__RequestMessage",
  "netlink.proto",
  sizeof(Netlink__Proto__RequestMessage),
  6,
  netlink__proto__request_message__field_descriptors,
  netlink__proto__request_message__field_indices_by_name,
  2,  netlink__proto__request_message__number_ranges,
  (ProtobufCMessageInit) netlink__proto__request_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__dpi_speed_item__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__DpiSpeedItem, type),
    &netlink__proto__dpi_level_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__DpiSpeedItem, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ifidx",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__DpiSpeedItem, ifidx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dpiId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__DpiSpeedItem, dpiid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rxSpeed",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__DpiSpeedItem, rxspeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txSpeed",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__DpiSpeedItem, txspeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__dpi_speed_item__field_indices_by_name[] = {
  3,   /* field[3] = dpiId */
  2,   /* field[2] = ifidx */
  4,   /* field[4] = rxSpeed */
  5,   /* field[5] = txSpeed */
  0,   /* field[0] = type */
  1,   /* field[1] = uid */
};
static const ProtobufCIntRange netlink__proto__dpi_speed_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor netlink__proto__dpi_speed_item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.DpiSpeedItem",
  "DpiSpeedItem",
  "Netlink__Proto__DpiSpeedItem",
  "netlink.proto",
  sizeof(Netlink__Proto__DpiSpeedItem),
  6,
  netlink__proto__dpi_speed_item__field_descriptors,
  netlink__proto__dpi_speed_item__field_indices_by_name,
  1,  netlink__proto__dpi_speed_item__number_ranges,
  (ProtobufCMessageInit) netlink__proto__dpi_speed_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__response_get_dpi_stream_speed__field_descriptors[1] =
{
  {
    "streamUidSpeed",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__ResponseGetDpiStreamSpeed, n_streamuidspeed),
    offsetof(Netlink__Proto__ResponseGetDpiStreamSpeed, streamuidspeed),
    &netlink__proto__dpi_speed_item__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__response_get_dpi_stream_speed__field_indices_by_name[] = {
  0,   /* field[0] = streamUidSpeed */
};
static const ProtobufCIntRange netlink__proto__response_get_dpi_stream_speed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netlink__proto__response_get_dpi_stream_speed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.ResponseGetDpiStreamSpeed",
  "ResponseGetDpiStreamSpeed",
  "Netlink__Proto__ResponseGetDpiStreamSpeed",
  "netlink.proto",
  sizeof(Netlink__Proto__ResponseGetDpiStreamSpeed),
  1,
  netlink__proto__response_get_dpi_stream_speed__field_descriptors,
  netlink__proto__response_get_dpi_stream_speed__field_indices_by_name,
  1,  netlink__proto__response_get_dpi_stream_speed__number_ranges,
  (ProtobufCMessageInit) netlink__proto__response_get_dpi_stream_speed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__response_get_wzry_server_ip__field_descriptors[1] =
{
  {
    "battleIp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__ResponseGetWzryServerIp, battleip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__response_get_wzry_server_ip__field_indices_by_name[] = {
  0,   /* field[0] = battleIp */
};
static const ProtobufCIntRange netlink__proto__response_get_wzry_server_ip__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netlink__proto__response_get_wzry_server_ip__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.ResponseGetWzryServerIp",
  "ResponseGetWzryServerIp",
  "Netlink__Proto__ResponseGetWzryServerIp",
  "netlink.proto",
  sizeof(Netlink__Proto__ResponseGetWzryServerIp),
  1,
  netlink__proto__response_get_wzry_server_ip__field_descriptors,
  netlink__proto__response_get_wzry_server_ip__field_indices_by_name,
  1,  netlink__proto__response_get_wzry_server_ip__number_ranges,
  (ProtobufCMessageInit) netlink__proto__response_get_wzry_server_ip__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__game_delay_stats__field_descriptors[10] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_ip_delay",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, rx_ip_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_udp_delay",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, rx_udp_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_user_delay",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, rx_user_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_udp_delay",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, tx_udp_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_ip_delay",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, tx_ip_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_sched_delay",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, tx_sched_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "down_packets",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, down_packets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "up_packets",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__GameDelayStats, up_packets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "down_delay_max",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Netlink__Proto__GameDelayStats, n_down_delay_max),
    offsetof(Netlink__Proto__GameDelayStats, down_delay_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__game_delay_stats__field_indices_by_name[] = {
  9,   /* field[9] = down_delay_max */
  7,   /* field[7] = down_packets */
  1,   /* field[1] = rx_ip_delay */
  2,   /* field[2] = rx_udp_delay */
  3,   /* field[3] = rx_user_delay */
  0,   /* field[0] = timestamp */
  5,   /* field[5] = tx_ip_delay */
  6,   /* field[6] = tx_sched_delay */
  4,   /* field[4] = tx_udp_delay */
  8,   /* field[8] = up_packets */
};
static const ProtobufCIntRange netlink__proto__game_delay_stats__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor netlink__proto__game_delay_stats__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.GameDelayStats",
  "GameDelayStats",
  "Netlink__Proto__GameDelayStats",
  "netlink.proto",
  sizeof(Netlink__Proto__GameDelayStats),
  10,
  netlink__proto__game_delay_stats__field_descriptors,
  netlink__proto__game_delay_stats__field_indices_by_name,
  1,  netlink__proto__game_delay_stats__number_ranges,
  (ProtobufCMessageInit) netlink__proto__game_delay_stats__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__response_get_game_delay__field_descriptors[1] =
{
  {
    "stats",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__ResponseGetGameDelay, n_stats),
    offsetof(Netlink__Proto__ResponseGetGameDelay, stats),
    &netlink__proto__game_delay_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__response_get_game_delay__field_indices_by_name[] = {
  0,   /* field[0] = stats */
};
static const ProtobufCIntRange netlink__proto__response_get_game_delay__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netlink__proto__response_get_game_delay__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.ResponseGetGameDelay",
  "ResponseGetGameDelay",
  "Netlink__Proto__ResponseGetGameDelay",
  "netlink.proto",
  sizeof(Netlink__Proto__ResponseGetGameDelay),
  1,
  netlink__proto__response_get_game_delay__field_descriptors,
  netlink__proto__response_get_game_delay__field_indices_by_name,
  1,  netlink__proto__response_get_game_delay__number_ranges,
  (ProtobufCMessageInit) netlink__proto__response_get_game_delay__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__response_message__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__ResponseMessage, header),
    &netlink__proto__message_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rspGetDpiStreamSpeed",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__ResponseMessage, response_data_case),
    offsetof(Netlink__Proto__ResponseMessage, rspgetdpistreamspeed),
    &netlink__proto__response_get_dpi_stream_speed__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rspWzryServerIp",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__ResponseMessage, response_data_case),
    offsetof(Netlink__Proto__ResponseMessage, rspwzryserverip),
    &netlink__proto__response_get_wzry_server_ip__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rspGameDelay",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__ResponseMessage, response_data_case),
    offsetof(Netlink__Proto__ResponseMessage, rspgamedelay),
    &netlink__proto__response_get_game_delay__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__response_message__field_indices_by_name[] = {
  0,   /* field[0] = header */
  3,   /* field[3] = rspGameDelay */
  1,   /* field[1] = rspGetDpiStreamSpeed */
  2,   /* field[2] = rspWzryServerIp */
};
static const ProtobufCIntRange netlink__proto__response_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 1 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor netlink__proto__response_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.ResponseMessage",
  "ResponseMessage",
  "Netlink__Proto__ResponseMessage",
  "netlink.proto",
  sizeof(Netlink__Proto__ResponseMessage),
  4,
  netlink__proto__response_message__field_descriptors,
  netlink__proto__response_message__field_indices_by_name,
  2,  netlink__proto__response_message__number_ranges,
  (ProtobufCMessageInit) netlink__proto__response_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__inform_message__field_descriptors[1] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__InformMessage, header),
    &netlink__proto__message_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__inform_message__field_indices_by_name[] = {
  0,   /* field[0] = header */
};
static const ProtobufCIntRange netlink__proto__inform_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netlink__proto__inform_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.InformMessage",
  "InformMessage",
  "Netlink__Proto__InformMessage",
  "netlink.proto",
  sizeof(Netlink__Proto__InformMessage),
  1,
  netlink__proto__inform_message__field_descriptors,
  netlink__proto__inform_message__field_indices_by_name,
  1,  netlink__proto__inform_message__number_ranges,
  (ProtobufCMessageInit) netlink__proto__inform_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__notify_wzry_server_ip__field_descriptors[1] =
{
  {
    "battleIp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__NotifyWzryServerIp, battleip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__notify_wzry_server_ip__field_indices_by_name[] = {
  0,   /* field[0] = battleIp */
};
static const ProtobufCIntRange netlink__proto__notify_wzry_server_ip__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor netlink__proto__notify_wzry_server_ip__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.NotifyWzryServerIp",
  "NotifyWzryServerIp",
  "Netlink__Proto__NotifyWzryServerIp",
  "netlink.proto",
  sizeof(Netlink__Proto__NotifyWzryServerIp),
  1,
  netlink__proto__notify_wzry_server_ip__field_descriptors,
  netlink__proto__notify_wzry_server_ip__field_indices_by_name,
  1,  netlink__proto__notify_wzry_server_ip__number_ranges,
  (ProtobufCMessageInit) netlink__proto__notify_wzry_server_ip__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netlink__proto__notify_message__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Netlink__Proto__NotifyMessage, header),
    &netlink__proto__message_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notifyWzryServerIp",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Netlink__Proto__NotifyMessage, notify_data_case),
    offsetof(Netlink__Proto__NotifyMessage, notifywzryserverip),
    &netlink__proto__notify_wzry_server_ip__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netlink__proto__notify_message__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = notifyWzryServerIp */
};
static const ProtobufCIntRange netlink__proto__notify_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor netlink__proto__notify_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "netlink.proto.NotifyMessage",
  "NotifyMessage",
  "Netlink__Proto__NotifyMessage",
  "netlink.proto",
  sizeof(Netlink__Proto__NotifyMessage),
  2,
  netlink__proto__notify_message__field_descriptors,
  netlink__proto__notify_message__field_indices_by_name,
  2,  netlink__proto__notify_message__number_ranges,
  (ProtobufCMessageInit) netlink__proto__notify_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue netlink__proto__netlink_msg_id__enum_values_by_number[10] =
{
  { "COMM_NETLINK_EVENT_UNSPEC", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_UNSPEC", 0 },
  { "COMM_NETLINK_EVENT_SET_DPI_UID", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_SET_DPI_UID", 11 },
  { "COMM_NETLINK_EVENT_GET_DPI_STREAM_SPEED", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_GET_DPI_STREAM_SPEED", 12 },
  { "COMM_NETLINK_EVENT_GET_ALL_UID_DPI_SPEED", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_GET_ALL_UID_DPI_SPEED", 13 },
  { "COMM_NETLINK_EVENT_SET_DPI_MATCH_ALL_UID", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_SET_DPI_MATCH_ALL_UID", 14 },
  { "COMM_NETLINK_EVENT_GET_WZRY_SERVER_IP", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_GET_WZRY_SERVER_IP", 51 },
  { "COMM_NETLINK_EVENT_NOTIFY_WZRY_SERVER_IP", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_NOTIFY_WZRY_SERVER_IP", 52 },
  { "COMM_NETLINK_EVENT_GET_WZRY_DATA", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_GET_WZRY_DATA", 53 },
  { "COMM_NETLINK_EVENT_GET_DELAY", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_GET_DELAY", 54 },
  { "COMM_NETLINK_EVENT_SET_LOG_STREAM_IPADDR", "NETLINK__PROTO__NETLINK_MSG_ID__COMM_NETLINK_EVENT_SET_LOG_STREAM_IPADDR", 101 },
};
static const ProtobufCIntRange netlink__proto__netlink_msg_id__value_ranges[] = {
{0, 0},{11, 1},{51, 5},{101, 9},{0, 10}
};
static const ProtobufCEnumValueIndex netlink__proto__netlink_msg_id__enum_values_by_name[10] =
{
  { "COMM_NETLINK_EVENT_GET_ALL_UID_DPI_SPEED", 3 },
  { "COMM_NETLINK_EVENT_GET_DELAY", 8 },
  { "COMM_NETLINK_EVENT_GET_DPI_STREAM_SPEED", 2 },
  { "COMM_NETLINK_EVENT_GET_WZRY_DATA", 7 },
  { "COMM_NETLINK_EVENT_GET_WZRY_SERVER_IP", 5 },
  { "COMM_NETLINK_EVENT_NOTIFY_WZRY_SERVER_IP", 6 },
  { "COMM_NETLINK_EVENT_SET_DPI_MATCH_ALL_UID", 4 },
  { "COMM_NETLINK_EVENT_SET_DPI_UID", 1 },
  { "COMM_NETLINK_EVENT_SET_LOG_STREAM_IPADDR", 9 },
  { "COMM_NETLINK_EVENT_UNSPEC", 0 },
};
const ProtobufCEnumDescriptor netlink__proto__netlink_msg_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "netlink.proto.NetlinkMsgId",
  "NetlinkMsgId",
  "Netlink__Proto__NetlinkMsgId",
  "netlink.proto",
  10,
  netlink__proto__netlink_msg_id__enum_values_by_number,
  10,
  netlink__proto__netlink_msg_id__enum_values_by_name,
  4,
  netlink__proto__netlink_msg_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue netlink__proto__dpi_level_type__enum_values_by_number[5] =
{
  { "DPI_LEVEL_UNSPEC", "NETLINK__PROTO__DPI_LEVEL_TYPE__DPI_LEVEL_UNSPEC", 0 },
  { "DPI_LEVEL_UID", "NETLINK__PROTO__DPI_LEVEL_TYPE__DPI_LEVEL_UID", 1 },
  { "DPI_LEVEL_APP", "NETLINK__PROTO__DPI_LEVEL_TYPE__DPI_LEVEL_APP", 2 },
  { "DPI_LEVEL_FUNC", "NETLINK__PROTO__DPI_LEVEL_TYPE__DPI_LEVEL_FUNC", 3 },
  { "DPI_LEVEL_STREAM", "NETLINK__PROTO__DPI_LEVEL_TYPE__DPI_LEVEL_STREAM", 4 },
};
static const ProtobufCIntRange netlink__proto__dpi_level_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex netlink__proto__dpi_level_type__enum_values_by_name[5] =
{
  { "DPI_LEVEL_APP", 2 },
  { "DPI_LEVEL_FUNC", 3 },
  { "DPI_LEVEL_STREAM", 4 },
  { "DPI_LEVEL_UID", 1 },
  { "DPI_LEVEL_UNSPEC", 0 },
};
const ProtobufCEnumDescriptor netlink__proto__dpi_level_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "netlink.proto.dpiLevelType",
  "dpiLevelType",
  "Netlink__Proto__DpiLevelType",
  "netlink.proto",
  5,
  netlink__proto__dpi_level_type__enum_values_by_number,
  5,
  netlink__proto__dpi_level_type__enum_values_by_name,
  1,
  netlink__proto__dpi_level_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
