// SPDX-License-Identifier: GPL-2.0-only
/*
* Copyright (C) 2022-2030 Oplus. All rights reserved.
*/
#ifndef __THEIA_SEND_EVENT_H_
#define __THEIA_SEND_EVENT_H_

#include <linux/types.h>

typedef enum {
	THEIA_EVENT_APP_BOOT_TIMEOUT = 0x0001,
	THEIA_EVENT_ACTIVITY_PAUSE_TIMEOUT,
	THEIA_EVENT_ANR,
	THEIA_EVENT_UITIMEOUT,
	THEIA_EVENT_NFW = 0x0101,
	THEIA_EVENT_TRANSPARENT_WINDOW,
	THEIA_EVENT_SWITCH_ANIMATION_TIMEOUT,
	THEIA_EVENT_ALL_WIN_DRAW_TIMEOUT,
	THEIA_EVENT_SCREEN_FROZEN,
	THEIA_EVENT_BLACK_SCREEN_HANG = 0x0201,
	THEIA_EVENT_BRIGHT_SCREEN_HANG,
	THEIA_EVENT_SENSOR_MONITOR_NEAR,
	THEIA_EVENT_SENSOR_MONITOR_FAR,
	THEIA_EVENT_SYSTEM_SERVER_HALF_WATCHDOG = 0x0301,
	THEIA_EVENT_FRAMEWORK_BLOCK,
	THEIA_EVENT_SF_HANG_WARNNING = 0x0401,
	THEIA_EVENT_SF_HANG,
	THEIA_EVENT_HECATE = 0x0411,
	THEIA_EVENT_HUNGTASK = 0x0501,
	THEIA_EVENT_INIT_HANG = 0x0503,
	THEIA_EVENT_LAUNCHER_CRASH = 0x0601,
	THEIA_EVENT_LAUNCHER_ANR,
	THEIA_EVENT_SYSTEMUI_CRASH = 0x0701,
	THEIA_EVENT_SYSTEMUI_ANR,
	THEIA_EVENT_PTR_TIMEOUT_HANG = 0x801,
	THEIA_EVENT_PTR_TIMEOUT_BLACKSCREEN,
	THEIA_EVENT_FDLEAK,
	THEIA_EVENT_HARDWARE_ERROR = 0x812,
	THEIA_EVENT_PWK_PANIC = 0x0F01,
	THEIA_EVENT_HOMEKEY_PANIC,
	THEIA_EVENT_BACKKEY_PANIC,
	THEIA_EVENT_PWK_LONGPRESS,
	THEIA_EVENT_TOUCHPANEL_PANIC,
	THEIA_EVENT_TRIGGER_ERROR_UPLOAD = 0x0E01,
	THEIA_EVENT_KPDPWR_RESIN_BARK,
} THEIA_EVENT_ID;

typedef enum  {
	THEIA_LOGINFO_ANDROID_LOG = 0x00000001,
	THEIA_LOGINFO_KERNEL_LOG = 0x00000002,
	THEIA_LOGINFO_ANR_TRACES = 0x00000004,
	THEIA_LOGINFO_DUMPSYS_SF = 0x00000008,
	THEIA_LOGINFO_DUMPSYS_MEMINFO = 0x00000010,
	THEIA_LOGINFO_BINDER_INFO = 0x00000020,
} THEIA_LOG_INFO;

void theia_send_event(THEIA_EVENT_ID id, unsigned int log_info, pid_t pid, const char *extra_info);
int theia_send_event_atomic(THEIA_EVENT_ID id, unsigned int log_info, const char *extra_info);
#endif /* __THEIA_SEND_EVENT_H_ */
